KERNEL_DEVICETREE = "axiado/axiado-evk-mt2.dtb"
KERNEL_DEVICETREE += "axiado/axiado-evk-sb2.dtb"
KERNEL_DEVICETREE += "axiado/ax3080a1s_hv2.dtb"
KERNEL_DEVICETREE += "axiado/mts2.dtb"

UBOOT_MACHINE ?= "ax3000_evk_defconfig"
KBUILD_DEFCONFIG ?= "axiado_defconfig"

require conf/machine/include/ax3000.inc
require conf/machine/include/ax3000-intern.inc
require conf/machine/include/obmc-evb-common.inc

WKS_FILE = "emmc-evk-axiado.wks.in"

FLASH_SIZE = "65535"
SERIAL_CONSOLES = "115200;ttyPS3"

OBMC_COMPATIBLE_NAMES = "ax3000"
EXTENDED_VERSION = "${DISTRO_VERSION}"

# Install Kernel modules
MACHINE_EXTRA_RRECOMMENDS = "kernel-modules"

IMAGE_FEATURES:remove = " \
    obmc-chassis-mgmt \
    obmc-chassis-state-mgmt \
    obmc-fan-control \
    obmc-fan-mgmt \
    obmc-host-ipmi \
    obmc-host-state-mgmt \
    obmc-ikvm \
"
IMAGE_FEATURES += "package-management"

VIRTUAL-RUNTIME_obmc-inventory-manager = "entity-manager"
VIRTUAL-RUNTIME_obmc-sensors-hwmon = "dbus-sensors"

# Fix sysproxy build error
DEBUG_PREFIX_MAP:remove = "-fcanon-prefix-map"
