KERNEL_DEVICETREE = "axiado/ax3000-scm3003-evk.dtb"
KERNEL_DEVICETREE += "axiado/ax3000-scm3002-evk.dtb"
KERNEL_DEVICETREE += "axiado/ax3080-evk.dtb"
KERNEL_DEVICETREE += "axiado/scm3080-mt-evk.dtb"

UBOOT_MACHINE ?= "ax3000_evk_defconfig"
KBUILD_DEFCONFIG ?= "ax3000_defconfig"

require conf/machine/include/ax3000.inc
require conf/machine/include/obmc-evb-common.inc

PREFERRED_VERSION_u-boot-axiado = "2019.04+git"
PREFERRED_VERSION_linux-axiado = "6.6.106+git"
PREFERRED_VERSION_sysproxy = "0.1"
PREFERRED_VERSION_tdfu = "0.1"
PREFERRED_VERSION_provision = "0.1"
PREFERRED_VERSION_logmgr = "0.1"

WKS_FILE = "emmc-evk-axiado.wks.in"

FLASH_SIZE = "65535"
SERIAL_CONSOLES = "115200;ttyPS3"

OBMC_COMPATIBLE_NAMES = "ax3000"
EXTENDED_VERSION = "${DISTRO_VERSION}"

# Install Kernel modules
MACHINE_EXTRA_RRECOMMENDS = "kernel-modules"

IMAGE_FEATURES:remove = " \
    obmc-chassis-mgmt \
    obmc-chassis-state-mgmt \
    obmc-fan-control \
    obmc-fan-mgmt \
    obmc-host-ipmi \
    obmc-host-state-mgmt \
"

VIRTUAL-RUNTIME_obmc-inventory-manager = "entity-manager"
VIRTUAL-RUNTIME_obmc-sensors-hwmon = "dbus-sensors"
