# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend \
            ${LAYERDIR}/recipes-*/*/*/*.bbappend \
            "

BBFILE_COLLECTIONS += "evb-axiado"
BBFILE_PATTERN_evb-axiado = "^${LAYERDIR}/"
LAYERSERIES_COMPAT_evb-axiado = "wrynose whinlatter"
